// flow-typed signature: a1363fd9432bbd8f6c3bbb7921631916
// flow-typed version: <<STUB>>/del_v^2.1.0/flow_v0.49.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'del'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'del' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'del/index' {
  declare module.exports: $Exports<'del'>;
}
declare module 'del/index.js' {
  declare module.exports: $Exports<'del'>;
}
