// flow-typed signature: 80c2c9db2b33b454e72f085dd0260a9a
// flow-typed version: <<STUB>>/fela-native_v^4.1.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fela-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fela-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'fela-native/index' {
  declare module.exports: $Exports<'fela-native'>;
}
declare module 'fela-native/index.js' {
  declare module.exports: $Exports<'fela-native'>;
}
